### ISSUE TITLE
All examples panic at unreachable.

### ISSUE THREAD

**Issue by biluohc** [jtomschroeder/cedar#25]
Use the last cedar that cloned from github.

rustc 1.28.0-nightly (e3bf634e0 2018-06-28)

openSUSE_Tumbleweed 20180618(x86_64 Linux 4.17.1-1-default)

GNOME  3.28.2

libwebkit2gtk-4_0-37-2.20.3-1.1.x86_64

```sh
thread 'main' panicked at 'internal error: entered unreachable code', /home/mxo/.cargo/registry/src/github.com-1ecc6299db9ec823/web-view-0.2.1/src/lib.rs:198:3
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:445
   6: web_view::handler_dispatch
             at ./<panic macros>:3
   7: webview_dispatch_wrapper
             at webview/webview.h:457
   8: <unknown>
   9: g_main_context_dispatch
  10: <unknown>
  11: g_main_context_iteration
  12: gtk_main_iteration_do
  13: webview_loop
             at webview/webview.h:351
  14: web_view::run
             at /home/mxo/.cargo/registry/src/github.com-1ecc6299db9ec823/web-view-0.2.1/src/lib.rs:90
  15: <cedar::application::Program<M, S>>::run
             at /home/mxo/Downloads/cache/cedar/src/application.rs:127
  16: <cedar::application::Application<M, S>>::run
             at /home/mxo/Downloads/cache/cedar/src/application.rs:42
  17: todo::main
             at src/main.rs:263
  18: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by jtomschroeder** [comment]
Hmm so far I've really only tested on macOS and that error seems to be coming from within `web_view` within GTK. It *should* work, but apparently not. I'll spin up a Linux environment and give it a test.
